# Generated by Django 5.2.7 on 2025-11-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='mensaje',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='nombre',
            new_name='nombre_usuario',
        ),
        migrations.AddField(
            model_name='ticket',
            name='asunto',
            field=models.CharField(default='Asunto pendiente', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
